Vertical Candidate List=False
WheelForPaging=True
Font="Source Han Serif CN 11"
MenuFont="Source Han Serif SC 11"
TrayFont="Fira Code 11"
TrayOutlineColor=#000000
TrayTextColor=#ffffff
PreferTextIcon=True
ShowLayoutNameInIcon=False
UseInputMethodLanguageToDisplayText=False
Theme=default
DarkTheme=default-dark
UseDarkTheme=True
UseAccentColor=False
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=False
UseHalfWidthPunctuation=True
