# Page size
PageSize=5
# Enable emoji in hint
EnableEmoji=False
# Enable emoji in quickphrase
EnableQuickPhraseEmoji=False
# Choose key modifier
Choose Modifier=Alt
# Enable hint by default
EnableHintByDefault=False
# Use new compose behavior
UseNewComposeBehavior=True
# Type special characters with long press
EnableLongPress=False
# Applications disabled for long press
LongPressBlocklist=

[PrevCandidate]
0=Up
1=Left

[NextCandidate]
0=Down
1=Right

[Hint Trigger]
0=Control+Alt+H

[One Time Hint Trigger]
0=Control+Alt+J

