[build]
rustflags = [
    "-C", "target-cpu=znver3"
]
[target.'cfg(windows)']
rustflags = [
    "--cfg", "windows_slim_errors"
]
[target.'cfg(unix)']
rustflags = [
]

[registries.crates-io]
protocol = "sparse"

[net]
git-fetch-with-cli = true
[http]
proxy = ""
[https]
proxy = ""
